config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'blog_posts#index'
  resources :blog_posts
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  validates :title, :content, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.order("created_at DESC")
  end

  def show
    @blog_post = get_blog_post(params[:id])
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to blog_posts_path, notice: 'This blog post was created successfully.'
    else
      render 'new'
    end
  end

  def edit
    @blog_post = get_blog_post(params[:id])
  end

  def update
    @blog_post = get_blog_post(params[:id])
    if @blog_post.update(blog_post_params)
      redirect_to blog_posts_path, notice: 'This blog post was updated successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @blog_post = get_blog_post(params[:id])
    @blog_post.destroy
    flash[:notice] = 'This blog post was destroyed successfully.'
    redirect_to root_path
  end

private

  def get_blog_post(id)
    BlogPost.find(id)
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for @blog_post, html: {role: 'form', class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.cktext_area :content, rows: 10, class: 'form-control', placeholder: 'Start Date' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/blog_posts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p class="navbar-btn"><%= link_to 'New Blog Post', new_blog_post_path, class: 'btn btn-primary' %></p>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/blog_posts/_validation.html.erb
<div class="row mid-full error">
  <div class="col-xs-12">
    <h3><b>Oops! <%= pluralize(@blog_post.errors.count, 'Error') %>:</b></h3>
    <ul>
      <% @blog_post.errors.full_messages.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/blog_posts/edit.html.erb
<% content_for :title do %>
  <title>Edit Blog Post</title>
<% end %>

<%= render 'header' %>

<div class="container">
  <% if @blog_post.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row mid-full">
    <div class="col-xs-12">
      <h1>Edit Blog Post</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/blog_posts/index.html.erb
<% content_for :title do %>
  <title> Home | CKEditor App</title>
<% end %>

<%= render 'header' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="text-center">CKEditor Ruby on Rails Application</h1>
      <div class="table-responsive">
        <table class="table table-stripped table-bordered table-hover">
          <tr>
            <th>Post ID</th>
            <th>Title</th>
            <th>Actions</th>
          </tr>
          <% if @blog_posts.any? %>
            <% @blog_posts.each do |blog_post| %>
              <tr>
                <td><%= blog_post.id %></td>
                <td><%= link_to blog_post.title.html_safe, blog_post_path(blog_post) %></td>
                <td>
                  <%= link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-primary' %>
                  <%= link_to 'Delete', blog_post_path(blog_post), method: :delete, class: 'btn btn-danger' %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="4" class="text-center">
                <p class="text-muted"><b>You don't have any blog posts yet.</b></p>
                <%= link_to 'Create a New Blog Post', new_blog_post_path, class: 'btn btn-primary btn-lg' %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/blog_posts/new.html.erb
<% content_for :title do %>
  <title>Create Blog Post</title>
<% end %>

<%= render 'header' %>

<div class="container">
  <% if @blog_post.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row mid-full">
    <div class="col-xs-12">
      <h1>Add a New Blog Post</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/blog_posts/show.html.erb
<% content_for :title do %>
  <title> Blog Post | CKEditor App</title>
<% end %>

<%= render 'header' %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-brand">Showing Blog Post</p>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p class="navbar-btn"><%= link_to 'Back', :back, class: 'btn btn-default' %>&nbsp;&nbsp;</p>
        </li>
        <li>
          <p class="navbar-btn"><%= link_to 'Edit', edit_blog_post_path(@blog_post), class: 'btn btn-primary' %>&nbsp;&nbsp;</p>
        </li>
        <li>
          <p class="navbar-btn"><%= link_to 'Delete', blog_post_path(@blog_post), method: :delete, class: 'btn btn-danger' %></p>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <h3>Title:</h3>
      <h1><%= @blog_post.title %></h1>
      <hr>
      <h3>Content:</h3>
      <div>
        <%= @blog_post.content.html_safe %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= yield :title %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success fade in alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger fade in alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <footer>
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 text-center">
            <p class="text-muted">Copyright &copy; 2016 by Abraar Arique Diganto. All rights reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>